name: Github Action No. 2

on:
  push: branches:["master"]

jobs:
  build:
    runs-on: ubuntu-letest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with: node-version:"18"

      - name: Install Dependencies
        run: npm ci
      - name: Build Project
        run: npm run build
